### ISSUE TITLE
"iOS 9 task switcher animation"

### ISSUE THREAD

**Issue by LeoNatan** [ltebean/LTInfiniteScrollView-Swift#1]
Hi,

Very cool framework!
Do you mind adding the "iOS 9 task switcher animation" gif source to the demo project?

Thanks,
Leo

**Comment by ltebean** [comment]
Thanks, you can find the implementation here: https://github.com/ltebean/LTInfiniteScrollView/blob/master/LTInfiniteScrollView/TaskSwitcherViewController.m

Btw, the view's tag is its index
