### ISSUE TITLE
Crash when using show(push) viewcontroller

### ISSUE THREAD

**Issue by leovu0703vn** [ltebean/LTInfiniteScrollView-Swift#3]
Hi sir,
I'm using your pod. But I have the problem that my app crash when I press a button to show the viewController that contain the UIView with LTInfiniteScrollView as its subclass.

If I set the viewController with LTInfiniteScrollView , the crash won't happen. As I tried to see the problem, I recognized that when I push/show the viewController. 

private func setup() {

```
    scrollView = UIScrollView(frame: CGRectMake(0, 0, CGRectGetWidth(self.bounds), CGRectGetHeight(self.bounds)))
    scrollView.autoresizingMask = [UIViewAutoresizing.FlexibleWidth, UIViewAutoresizing.FlexibleHeight]
    scrollView.showsHorizontalScrollIndicator = false
    scrollView.delegate = self
    scrollView.clipsToBounds = false
    self.addSubview(scrollView)
}
```

this setup is not work. 
I tried to put this code in to this ,it wasn't crash. but the scrollview is laid behind the uiviewController now.

let rv = UIApplication.sharedApplication().keyWindow!.subviews.last! as UIView
rv.addSubview(self.scrollView)

Can you help me to fix this problem? I'm a Swift beginner so please help me, I really need your pod to fix my problem.

**Comment by ltebean** [comment]
I don't quite understand the problem from what you said, can you send the code to me

**Comment by leovu0703vn** [comment]
At ViewControllerA, I have a button which have show/push via segue to ViewControllerB. At ViewControllerB, I have a UIView using LTInfiniteScrollView as Custom Class. When I click the button at ViewControllerA , my app crashed at this line 

currentIndex = Int(round((currentCenterX - viewSize.width / 2) / viewSize.width))

But when I set ViewControllerB as Is Initial View Controller, the app work perfectly.

**Comment by leovu0703vn** [comment]
I used the codes like your example except I used a ViewControllerA with button to show/push to ViewControllerB which contains LTInfiniteScrollView.

**Comment by ltebean** [comment]
Just create a test branch, the vc contains LTInfiniteScrollView is pushed by another vc, and it works fine, can you modify the code to reproduce the error?

**Comment by ltebean** [comment]
https://github.com/ltebean/LTInfiniteScrollView-Swift/tree/test

**Comment by leovu0703vn** [comment]
thank you. Thanks to your test . I recognized that my crash problem happened because of my ViewControllerB embed in a navigation controller. Is there anyway to fix this?

**Comment by ltebean** [comment]
can you paste the crash log

**Comment by leovu0703vn** [comment]
LTInfiniteScrollView-Swift[78079:957510] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing a navigation controller is not supported'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001099d7d85 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010be43deb objc_exception_throw + 48
    2   UIKit                               0x000000010aaab8c9 __71-[UINavigationController pushViewController:transition:forceImmediate:]_block_invoke + 0
    3   UIKit                               0x000000010aaaabf5 -[UINavigationController pushViewController:animated:] + 848
    4   UIKit                               0x000000010b095c44 __66-[UIStoryboardPushSegueTemplate newDefaultPerformHandlerForSegue:]_block_invoke + 1660
    5   UIKit                               0x000000010b00f630 -[UIStoryboardSegueTemplate _performWithDestinationViewController:sender:] + 460
    6   UIKit                               0x000000010b00f433 -[UIStoryboardSegueTemplate _perform:] + 82
    7   UIKit                               0x000000010b00f6f7 -[UIStoryboardSegueTemplate perform:] + 156
    8   UIKit                               0x000000010a8c9a8d -[UIApplication sendAction:to:from:forEvent:] + 92
    9   UIKit                               0x000000010aa3ce67 -[UIControl sendAction:to:forEvent:] + 67
    10  UIKit                               0x000000010aa3d143 -[UIControl _sendActionsForEvents:withEvent:] + 327
    11  UIKit                               0x000000010aa3c263 -[UIControl touchesEnded:withEvent:] + 601
    12  UIKit                               0x000000010a93c99f -[UIWindow _sendTouchesForEvent:] + 835
    13  UIKit                               0x000000010a93d6d4 -[UIWindow sendEvent:] + 865
    14  UIKit                               0x000000010a8e8dc6 -[UIApplication sendEvent:] + 263
    15  UIKit                               0x000000010a8c2553 _UIApplicationHandleEventQueue + 6660
    16  CoreFoundation                      0x00000001098fd301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    17  CoreFoundation                      0x00000001098f322c __CFRunLoopDoSources0 + 556
    18  CoreFoundation                      0x00000001098f26e3 __CFRunLoopRun + 867
    19  CoreFoundation                      0x00000001098f20f8 CFRunLoopRunSpecific + 488
    20  GraphicsServices                    0x000000010f47dad2 GSEventRunModal + 161
    21  UIKit                               0x000000010a8c7f09 UIApplicationMain + 171
    22  LTInfiniteScrollView-Swift          0x00000001097d4dc2 main + 114
    23  libdyld.dylib                       0x000000010c90792d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ltebean** [comment]
The problem is, a navigation controller cannot push another navigation controller, so don't embed ViewControllerB in a navigation controller

**Comment by leovu0703vn** [comment]
but I have to use the navigation controller in the ViewControllerB , so I deleted the navigation controller in ViewControllerA and this is the new crash log. 

LTInfiniteScrollView-Swift[79678:970049] **\* Terminating app due to uncaught exception 'NSGenericException', reason: 'Push segues can only be used when the source controller is managed by an instance of UINavigationController.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x0000000109d4fd85 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010c1bbdeb objc_exception_throw + 48
    2   UIKit                               0x000000010b40dca9 __copy_helper_block_ + 0
    3   UIKit                               0x000000010b387630 -[UIStoryboardSegueTemplate _performWithDestinationViewController:sender:] + 460
    4   UIKit                               0x000000010b387433 -[UIStoryboardSegueTemplate _perform:] + 82
    5   UIKit                               0x000000010b3876f7 -[UIStoryboardSegueTemplate perform:] + 156
    6   UIKit                               0x000000010ac41a8d -[UIApplication sendAction:to:from:forEvent:] + 92
    7   UIKit                               0x000000010adb4e67 -[UIControl sendAction:to:forEvent:] + 67
    8   UIKit                               0x000000010adb5143 -[UIControl _sendActionsForEvents:withEvent:] + 327
    9   UIKit                               0x000000010adb4263 -[UIControl touchesEnded:withEvent:] + 601
    10  UIKit                               0x000000010acb499f -[UIWindow _sendTouchesForEvent:] + 835
    11  UIKit                               0x000000010acb56d4 -[UIWindow sendEvent:] + 865
    12  UIKit                               0x000000010ac60dc6 -[UIApplication sendEvent:] + 263
    13  UIKit                               0x000000010ac3a553 _UIApplicationHandleEventQueue + 6660
    14  CoreFoundation                      0x0000000109c75301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    15  CoreFoundation                      0x0000000109c6b22c __CFRunLoopDoSources0 + 556
    16  CoreFoundation                      0x0000000109c6a6e3 __CFRunLoopRun + 867
    17  CoreFoundation                      0x0000000109c6a0f8 CFRunLoopRunSpecific + 488
    18  GraphicsServices                    0x000000010f7f5ad2 GSEventRunModal + 161
    19  UIKit                               0x000000010ac3ff09 UIApplicationMain + 171
    20  LTInfiniteScrollView-Swift          0x0000000109b4cdc2 main + 114
    21  libdyld.dylib                       0x000000010cc7f92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by ltebean** [comment]
in vcA, you can present a navigation controller with vcB

**Comment by leovu0703vn** [comment]
thank you for your helping. 👍
